seed: 17
model:
  name: hf_causal_lm
  pretrained: true
  init_device: mixed
  config_overrides:
    attn_config:
      attn_impl: triton
      attn_uses_sequence_id: false
  pretrained_model_name_or_path: mosaicml/mpt-7b
loggers: {}
callbacks:
  lr_monitor: {}
  scheduled_gc:
    batch_interval: 1000
  speed_monitor:
    window_size: 10
  memory_monitor: {}
optimizer:
  lr: 5.0e-07
  name: decoupled_lionw
  betas:
  - 0.9
  - 0.95
  weight_decay: 0
precision: amp_bf16
scheduler:
  name: linear_decay_with_warmup
  alpha_f: 0
  t_warmup: 0.02dur
tokenizer:
  name: mosaicml/mpt-7b
  kwargs:
    model_max_length: 2048
algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1
autoresume: true
fsdp_config:
  verbose: false
  mixed_precision: PURE
  limit_all_gathers: true
  sharding_strategy: FULL_SHARD
  activation_cpu_offload: false
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
global_seed: 17
max_seq_len: 2048
save_folder: oci://irene-test/finetuning/finetune-mpt-7b-7UuaqM/checkpoints
max_duration: 10ba
progress_bar: false
train_loader:
  name: finetuning
  dataset:
    split: train
    packing_ratio: auto
    hf_name: mosaicml/dolly_hhrlhf
    shuffle: true
    max_seq_len: 2048
    shuffle_seed: 17
    allow_pad_trimming: false
    decoder_only_format: true
  timeout: 0
  drop_last: false
  pin_memory: true
  num_workers: 8
  prefetch_factor: 2
  persistent_workers: true
eval_interval: 1
save_interval: 1000ba
log_to_console: true
python_log_level: debug
save_weights_only: false
console_log_interval: 10ba
global_train_batch_size: 96
device_train_microbatch_size: auto
save_num_checkpoints_to_keep: 1
