max_seq_len: 100
global_seed: 17

# Run Name
run_name:  # If left blank, will be read from env var $RUN_NAME

# Model
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: 144
  n_heads: 2
  n_layers: 2
  expansion_ratio: 2
  max_seq_len: ${max_seq_len}
  vocab_size: 50368
  attn_config:
    attn_impl: flash

# Tokenizer
tokenizer:
  name: EleutherAI/gpt-neox-20b
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: finetuning
  dataset:
    split: train
    hf_name: mosaicml/dolly_hhrlhf
    shuffle: true
    max_seq_len: ${max_seq_len}
    packing_ratio: 1
    allow_pad_trimming: false
    decoder_only_format: true
  timeout: 0
  drop_last: false
  pin_memory: true
  num_workers: 8
  prefetch_factor: 2
  persistent_workers: true

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 6.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 1ba  # ~ 2.5B tokens
eval_subset_num_batches: -1
global_train_batch_size: 256

# System
seed: ${global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 16
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
  hf_checkpointer:
    precision: bfloat16
    save_interval: 1dur
    save_folder: s3://mosaicml-internal-checkpoints-shared/irene/3-29-test/
    mlflow_logging_config:
      metadata:
        task: llm/v1/completions
        pretrained_model_name: mpt125
        databricks_model_family: MPTForCausalLM
        databricks_model_size_parameters: 125m
        databricks_model_source: genai-fine-tuning
    mlflow_registered_model_name: mpt125test

loggers:
  mlflow:
    tracking_uri: databricks
    experiment_name: /Users/irene.dea@databricks.com/mpt125
    model_registry_uri: databricks-uc
    model_registry_prefix: main.irenedea
